Repository Triumers/KMS-Front, pull requests merged in 2024-05, with the labels that each got.

#3 [Feature] 게시글 관련 기본/추가 기능 구현
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
  src/main.js
  src/router/mainRouter.js
  src/views/PostView.vue
Labels: enhancement

#5 [Style] 일반게시글/위키 리스트 조회->단일 조회 연결
  src/App.vue
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
  src/router/mainRouter.js
Labels: bug, enhancement

#7 [Feature] 퀴즈 기본 기능
  .github/ISSUE_TEMPLATE/이슈-작성-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/components/common/Modal.vue
  src/components/post/SelectedPostDetail.vue
  src/components/quiz/CreateQuiz.vue
  src/components/quiz/TakeQuiz.vue
  src/main.js
  src/router/mainRouter.js
  src/views/QuizView.vue
Labels: enhancement

#8 [Design] 작성페이지 구조 및 디자인 수정
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
Labels: enhancement

#9 [Feature] Navigation Bar 생성
  .github/workflows/node.js.yml
  src/App.vue
  src/components/common/Navbar.vue
  src/router/mainRouter.js
  src/views/Group.vue
  src/views/OfficeLife.vue
  src/views/Organization.vue
  src/views/Study.vue
  src/views/Wiki.vue
  src/views/Workspace.vue
Labels: enhancement

#10 [Feature] 게시글 중간 파일 업로드/내용 미리보기/PDF 기능 구현
  package-lock.json
  package.json
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedPostDetail.vue
  src/main.js
Labels: enhancement

#11 [Refactor] mainRouter.js 경로 수정
  src/components/common/Navbar.vue
  src/router/mainRouter.js
Labels: enhancement

#12 [Refactor] 라우터 수정 및 임시 연결
  src/components/common/Navbar.vue
  src/components/post/CreateNewDocs.vue
  src/components/post/SelectedDocsList.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
  src/router/mainRouter.js
  src/views/Group.vue
  src/views/OfficeLife.vue
  src/views/Organization.vue
  src/views/Study.vue
  src/views/Wiki.vue
  src/views/Workspace.vue
  src/views/WorkspaceView.vue
Labels: bug, enhancement

#13 [Refactor] 포스트 데이터 연결 및 수정
  src/components/post/CreateNewDocs.vue
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedDocsList.vue
  src/components/post/SelectedPostList.vue
  src/router/mainRouter.js
  src/views/WorkspaceView.vue
Labels: refactor

#14 [Feature] 퀴즈 정답 제출 및 조회 기능
  src/components/common/Modal.vue
  src/components/post/SelectedPostDetail.vue
  src/components/quiz/TakeQuiz.vue
Labels: enhancement

#15 [Feature] 게시글 좋아요 회원 리스트 확인
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedPostDetail.vue
Labels: enhancement, refactor

#16 [Design] Header, Navbar 수정
  src/assets/images/logo_header.png
  src/components/common/Navbar.vue
  src/views/Header.vue
Labels: enhancement, refactor

#17 [Refactor] 라우터 경로 수정
  src/components/common/Navbar.vue
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
  src/router/mainRouter.js
Labels: refactor

#18 [Design] Header 구성 추가
  src/assets/icons/search_icon.png
  src/assets/images/profile_image.png
  src/views/Header.vue
Labels: enhancement
