Repository Triumers/KMS-Front, pull requests merged in 2024-06, with the labels that each got.

#20 [Feature] 익명게시판 기본 기능 구현
  src/components/anonymous-board/AnonymousBoardDetail.vue
  src/components/anonymous-board/AnonymousBoardList.vue
  src/components/anonymous-board/CreateNewAnonymousBoard.vue
  src/components/post/SelectedPostDetail.vue
  src/router/mainRouter.js
  src/views/AnonymousBoard.vue
Labels: enhancement

#21 [Refactor] 포트 번호 수정
  src/components/anonymous-board/AnonymousBoardDetail.vue
  src/components/anonymous-board/AnonymousBoardList.vue
  src/components/anonymous-board/CreateNewAnonymousBoard.vue
  src/components/post/SelectedPostDetail.vue
Labels: bug

#22 [Feature] 로그인 시 Token 발급 및 저장 구현
  src/components/user/Login.vue
  src/router/mainRouter.js
Labels: enhancement

#23 [Refactor] 게시글 관련 화면 수정
  src/components/common/Navbar.vue
  src/components/post/SelectedDocsList.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
  src/router/mainRouter.js
  src/views/Group.vue
  src/views/Header.vue
  src/views/OfficeLife.vue
  src/views/Wiki.vue
  src/views/Workspace.vue
  src/views/WorkspaceView.vue
Labels: refactor

#24 [Feature] 결재 기본 기능 구현
  src/components/approval/CreateApproval.vue
  src/components/approval/ReceivedApprovalDetail.vue
  src/components/approval/ReceivedApprovals.vue
  src/components/approval/RequestedApprovalDetail.vue
  src/components/approval/RequestedApprovals.vue
  src/router/mainRouter.js
  src/views/Approval.vue
Labels: enhancement

#26 [Refactor] 게시글 관련 기능 수정
  src/components/post/CreateNewDocs.vue
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SearchAllPostList.vue
  src/components/post/SelectedDocsList.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
Labels: refactor

#28 [Refactor] 결재 리스트 페이징 처리 및 상태별 조회에 취소됨 추가
  src/components/approval/CreateApproval.vue
  src/components/approval/ReceivedApprovals.vue
  src/components/approval/RequestedApprovals.vue
Labels: enhancement, refactor

#29 [Feature] 번역 기능 구현
  src/components/post/SelectedPostDetail.vue
Labels: enhancement

#30 [Feature] 관리자 탭 추가 모달창/페이징 처리
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SearchAllPostList.vue
  src/components/post/SelectedDocsList.vue
  src/components/post/SelectedPostList.vue
  src/router/mainRouter.js
  src/views/Profile.vue
  src/views/WorkspaceView.vue
Labels: enhancement, refactor

#31 [Feature] 회원 기본 기능 구현
  src/components/user/ChangePassword.vue
  src/components/user/EditMyInfo.vue
  src/components/user/FavoritePosts.vue
  src/components/user/LikedPosts.vue
  src/components/user/MyComments.vue
  src/components/user/MyPage.vue
  src/components/user/MyPosts.vue
  src/router/mainRouter.js
Labels: enhancement

#27 [Feature] 퀴즈 기본기능 개선 및 배포를 위한 파일 생성
  .github/workflows/node.js.yml
  Procfile
  server.js
  src/components/quiz/CreateQuiz.vue
  src/components/quiz/EditQuiz.vue
  src/components/quiz/QuizManagement.vue
Labels: enhancement, release

#33 [Refactor] 익명게시판 라우터 수정 및 경로 수정
  src/components/anonymous-board/AnonymousBoardDetail.vue
  src/components/anonymous-board/AnonymousBoardList.vue
  src/components/anonymous-board/CreateNewAnonymousBoard.vue
  src/components/common/Navbar.vue
Labels: refactor

#34 [Feature] 관리자 기본 기능 구현
  src/components/anonymous-board/AnonymousBoardDetail.vue
  src/components/manager/CreateUser.vue
  src/components/manager/EditUser.vue
  src/components/manager/EditUserRole.vue
  src/components/manager/ResetUserPassword.vue
  src/components/manager/SearchUser.vue
  src/components/user/Login.vue
  src/router/mainRouter.js
  src/views/Header.vue
  src/views/Manager.vue
Labels: enhancement

#35 [Refactor] Vuex 추가 후 관련된 코드 수정
  .env
  package-lock.json
  package.json
  src/components/anonymous-board/AnonymousBoardDetail.vue
  src/components/user/Login.vue
  src/components/user/MyPage.vue
  src/main.js
  src/router/mainRouter.js
  src/store/index.js
  src/views/Header.vue
  vite.config.js
Labels: refactor

#37 [Feature] 직원 조회 기능 구현 및 직책 관리, 직급 관리 기능 구현
  src/components/common/Navbar.vue
  src/components/employee/SearchEmployee.vue
  src/components/manager/ManagePosition.vue
  src/components/manager/ManageRank.vue
  src/components/manager/SearchUser.vue
  src/router/mainRouter.js
Labels: enhancement

#38 [Fix] 헤더에 버튼 안 보이는 오류 수정
  src/App.vue
  src/store/index.js
Labels: bug

#39 [Bug] 마이페이지 내가 좋아요/북마크 한 포스트
  src/components/post/SelectedDocsList.vue
  src/components/post/SelectedPostList.vue
  src/components/user/FavoritePosts.vue
  src/components/user/LikedPosts.vue
  src/views/Header.vue
  src/views/Study.vue
Labels: bug, refactor

#40 [Feature] 기본 비밀번호로 로그인 및 비밀번호 변경 시 로직 구현
  src/assets/images/pinkFlowerLeft.gif
  src/assets/images/pinkFlowerRight.gif
  src/components/user/ChangePassword.vue
  src/components/user/Login.vue
  src/components/user/Welcome.vue
  src/components/user/WelcomeToJoin.vue
  src/router/mainRouter.js
Labels: enhancement

#41 [Fix] 로그인 페이지 vuex 오류 수정
  src/components/user/Login.vue
Labels: bug

#42 [Fix] 로그인 시 오류 발생하는 부분 수정
  src/components/user/Login.vue
  src/store/index.js
Labels: bug

#44 [Feature] 조직도 기능 구현
  src/components/employee/SearchEmployee.vue
  src/components/organization/OrganizationChart.vue
Labels: enhancement

#45 [Refactor] 회원 생성 시 비밀번호를 따로 입력하지 않으면 초기 비밀번호로 되는 것으로 수정
  src/components/manager/CreateUser.vue
Labels: refactor

#46 [Fix] 사진 등록 및 출력 문제 해결
  src/components/user/EditMyInfo.vue
  src/components/user/MyPage.vue
  src/views/Header.vue
Labels: bug

#47 [Refactor] 비밀번호 변경 안내메시지 추가
  src/components/user/ChangePassword.vue
Labels: enhancement

#48 [Feature] 403 발생 시 로그인 페이지 리다이렉트 기능 구현
  src/main.js
  src/store/index.js
Labels: enhancement

#49 [Refactor] 게시글 불러오기 중복 처리
  src/components/post/SearchAllPostList.vue
  src/components/post/SelectedPostList.vue
  src/styles/post/PostList.css
Labels: refactor

#51 [Refactor] default 경로 import 수정
  src/components/post/SearchAllPostList.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
Labels: bug, refactor

#52 [Refactor] 마크다운 적용
  package-lock.json
  package.json
  src/components/post/CreateNewDocs.vue
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SearchAllPostList.vue
  src/components/post/SelectedPostDetail.vue
  src/components/post/SelectedPostList.vue
  src/main.js
Labels: refactor

#54 [Refactor] 첫 로그인 시 2차 인증 등록하도록 개선
  src/components/user/EditMyInfo.vue
  src/components/user/Login.vue
  src/components/user/OtpRegistration.vue
Labels: refactor

#53 [Refactor] 게시글 수정 시, 대표 이미지 세팅 추가
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SearchAllPostList.vue
  src/components/post/SelectedPostDetail.vue
Labels: refactor

#55 [Refactor] 익명게시판 글, 댓글 작성 시 닉네임 '익명'으로 고정
  src/components/anonymous-board/AnonymousBoardDetail.vue
  src/components/anonymous-board/CreateNewAnonymousBoard.vue
Labels: refactor

#57 [Feature] API_URL 주소 수정
  src/api/comment.js
Labels: bug

#58 [Feature] 익명게시판 댓글 하나씩 삭제하는 기능 구현 및 페이징 처리 수정
  src/components/anonymous-board/AnonymousBoardDetail.vue
Labels: enhancement, refactor

#60 [Refactor] 워크스페이스 및 스터디 생성 버튼 관리자 페이지로 이동 및 결재 유형 추가 기능 구현
  src/components/manager/SearchUser.vue
  src/components/user/MyPage.vue
Labels: enhancement, refactor

#61 [Feature] 서버 상태 조회 기능 구현
  src/components/common/HealthCheck.vue
  src/router/mainRouter.js
Labels: enhancement

#62 [Refactor] 서버 및 접속 상태 조회 개선
  src/components/common/HealthCheck.vue
Labels: bug

#63 [Refactor] 스터디, 워크스페이스에서 팀원 직접 추가하는 모달창 추가
  src/views/Study.vue
  src/views/WorkspaceView.vue
Labels: refactor

#64 [Refactor] 여러 디자인 및 기능 수정
  src/components/anonymous-board/AnonymousBoardDetail.vue
  src/components/common/Navbar.vue
  src/components/employee/SearchEmployee.vue
  src/components/organization/OrganizationChart.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SearchAllPostList.vue
  src/components/post/SelectedPostList.vue
  src/main.js
  src/styles/post/PostList.css
  src/views/Header.vue
  src/views/Organization.vue
Labels: bug, refactor

#65 [Fix] 내 정보 수정 프로필 이미지 등록 오류 수정
  src/components/user/EditMyInfo.vue
Labels: bug

#66 [Feature] 퀴즈 기본 기능 구현
  src/components/post/SelectedPostDetail.vue
  src/components/quiz/CreateQuiz.vue
  src/components/quiz/EditQuiz.vue
  src/components/quiz/TakeQuiz.vue
Labels: enhancement

#67 [Refactor] 포스트 이미지가 없을 경우, 내용 추가 표시 처리
  src/components/post/SelectedPostList.vue
  src/styles/post/PostList.css
Labels: refactor

#70 [Hotfix] 전체 검색도 리스트와 동일하게 포스트 이미지 처리 및 내비게이션 바에 점심 메뉴 추천 기능 구현
  src/components/common/Navbar.vue
  src/components/post/SearchAllPostList.vue
Labels: refactor

#71 [Refactor] 글씨체 적용, 워크스페이스 직원 추가 조건 설정, 안내 문구 추가
  src/App.vue
  src/components/post/CreateNewGeneralPost.vue
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedPostDetail.vue
  src/components/user/EditMyInfo.vue
  src/components/user/Login.vue
  src/main.js
  src/views/Study.vue
  src/views/WorkspaceView.vue
Labels: refactor

#72 [Hotfix] 링크 복사
  package-lock.json
  package.json
  src/components/post/CreateNewPost.vue
  src/components/post/SelectedPostDetail.vue
  src/main.js
Labels: refactor

#73 [Fix] 인사담당자 이상의 권한에서 회원 정보 변경 관련 버그 수정
  src/components/manager/EditUser.vue
  src/components/manager/EditUserRole.vue
  src/components/manager/ResetUserPassword.vue
Labels: bug

#74 [Fix] 인사담당자 이상의 권한에서 회원 정보 변경 관련 버그 수정
  src/components/manager/EditUser.vue
Labels: bug

#75 [Refactor] 비밀번호 초기화 개선
  src/components/manager/ResetUserPassword.vue
Labels: refactor
